services:
  db:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: sorteio
      POSTGRES_PASSWORD: sorteio
      POSTGRES_DB: sorteio_dev
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/data:/var/lib/postgresql/data
  
  app:
    build: .
    ports:
      - 4000:4000
    volumes:
      - .:/app
    depends_on:
      - db